lab2_MVC_Laura/Models/ClaseBisiesto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace lab2_MVC_Laura.Models
{
    public class ClaseBisiesto
    {
        public int inicio { get; set; }
        public int termino { get; set; }
        public string bisiesto { get; set; }
        public string nobisisesto { get; set; }
        public string resultado { get; set; }

        public string Todo { get; set; }


    }
}

lab2_MVC_Laura/Models/ClsBillete.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;

namespace lab2_MVC_Laura.Models
{
    public class ClsBillete
    {
        public int monto { get; set; }

        public int b100 { get; set; }

        public int b50 { get; set; }

        public int b20 { get; set; }

        public int b10 { get; set; }


    }
}

lab2_MVC_Laura/Models/ClsPersona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace lab2_MVC_Laura.Models
{
    public class ClsPersona
    {
      
        public string apellido { get; set; }

        public string nombre { get; set; }

        public string email { get; set; }

        public bool sexo { get; set; }

        public int edad { get; set; }

        public double talla { get; set; }

    }



}

lab2_MVC_Laura/Controllers/BilleteController.cs
using lab2_MVC_Laura.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab2_MVC_Laura.Controllers
{
    public class BilleteController : Controller
    {
        // GET: Billete
        // PRUEBA PARA LA MODIFICACION EN GITHUB DESDE VISUAL STUDIO
        // PRUEBA PARA LA MODIFICACION EN GITHUB DESDE VISUAL STUDIO
        // PRUEBA PARA LA MODIFICACION EN GITHUB DESDE VISUAL STUDIO
        // PRUEBA PARA LA MODIFICACION EN GITHUB DESDE VISUAL STUDIO
        // PRUEBA PARA LA MODIFICACION EN GITHUB DESDE VISUAL STUDIO
        // PRUEBA PARA LA MODIFICACION EN GITHUB DESDE VISUAL STUDIO

        public ActionResult github()
        {
            return View();
        }
        public ActionResult Visualizar(ClsBillete objBillete)
        {
            int cantidad;
            cantidad = objBillete.monto;
            int cant100, cant50, cant20, cant10;
            int rest100, res50, res20, res10;

            cant100 = cantidad / 100;
            rest100 = cantidad % 100;

            cant50 = rest100 / 50;
            res50 = rest100 % 50;


            cant20 = res50 / 20;
            res20 = res50 % 20;


            cant10 = res20 / 10;
            res10 = res20 % 10;

            objBillete.b100 = cant100;
            objBillete.b50 = cant50;
            objBillete.b20 = cant20;
            objBillete.b10 = cant10;


            return View(objBillete);
        }
    }
}

lab2_MVC_Laura/Controllers/BisiestoController.cs
using lab2_MVC_Laura.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab2_MVC_Laura.Controllers
{
    public class BisiestoController : Controller
    {
        // GET: Bisiesto

  
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Visualizar(ClaseBisiesto objBisiesto)
        {
            return View(objBisiesto);
        }

    }
}

lab2_MVC_Laura/Controllers/PersonaController.cs
using lab2_MVC_Laura.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab2_MVC_Laura.Controllers
{
    public class PersonaController : Controller
    {
        // ClsPersona clsPersona = new ClsPersona();
        List<ClsPersona> objLista = new List<ClsPersona>();

        public ActionResult Index()
        {
            //instanciar para el objetoi 1
            ClsPersona objPersona1 = new ClsPersona();
            //  Instanciar los atributos de  la clase

            objPersona1.apellido = "Porlles Carpio";
            objPersona1.nombre = "Diego";
            objPersona1.email = "porles@upt.pe";
            objPersona1.sexo = true;
            objPersona1.edad = 22;
            objPersona1.talla = 1.60;
            //pasar el objeto a la lista
            objLista.Add(objPersona1);


            //instanciar para el objetoi 1
            ClsPersona objPersona2= new ClsPersona();
            //  Instanciar los atributos de  la clase

            objPersona2.apellido = "Mamani Ayala";
            objPersona2.nombre = "Brandon";
            objPersona2.email = "bayala@upt.pe";
            objPersona2.sexo = true;
            objPersona2.edad = 23;
            objPersona2.talla = 1.65;
            //pasar el objeto a la lista
            objLista.Add(objPersona2);

            //instanciar para el objetoi 3
            ClsPersona objPersona3 = new ClsPersona();
            //  Instanciar los atributos de  la clase

            objPersona3.apellido = "Sosa Bedoya";
            objPersona3.nombre = "Sharon";
            objPersona3.email = "sharonbed@upt.pe";
            objPersona3.sexo = false;
            objPersona3.edad = 24;
            objPersona3.talla = 1.68;
            //pasar el objeto a la lista
            objLista.Add(objPersona3);


            //instanciar para el objetoi 1
            ClsPersona objPersona4 = new ClsPersona();
            //  Instanciar los atributos de  la clase

            objPersona4.apellido = "Estrella Pàlacios";
            objPersona4.nombre = "Katherine";
            objPersona4.email = "kestrella@upt.pe";
            objPersona4.sexo = false;
            objPersona4.edad = 25;
            objPersona4.talla = 1.72;
            //pasar el objeto a la lista
            objLista.Add(objPersona4);



            return View(objLista);
        }
    }
}

lab2_MVC_Laura/Views/Billete/Index.cshtml
@model lab2_MVC_Laura.Models.ClsBillete
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <h1>Cajero de Billetes</h1>
        <br /><br />
              <div>
                  @using (Html.BeginForm("visualizar", "Billete", FormMethod.Post))
                  {
                      <div>
                         
                          @Html.LabelFor(model => model.monto, "Ingresar monto: ")
                          @Html.TextBoxFor(model => model.monto)
                      </div>

                      <br /><br />
                      <input type="submit" value="Calcular" />
                      <br /><br />

                  }

              </div>
    </div>
</body>
</html>

lab2_MVC_Laura/Views/Billete/Visualizar.cshtml
@model lab2_MVC_Laura.Models.ClsBillete
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Visualizar</title>
</head>
<body>
    <div> 
        <h1>Cajero de billetes</h1>
        <div>
            <label>Monto: </label> @Model.monto <br /><br />
            <label>Billete de 100</label> @Model.b100 <br /><br />
            <label>Billete de 50 </label> @Model.b50 <br /><br />
            <label>Billete de 20 </label> @Model.b20 <br /><br />
            <label>MoBillete de 10 </label> @Model.b10 <br /><br />

        </div>
    </div>
    <br />
    <a href="Index"> << Retornar al Formulario </a>
        <br />

</body>
</html>

lab2_MVC_Laura/Views/Bisiesto/Index.cshtml
@model lab2_MVC_Laura.Models.ClaseBisiesto
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <h1>Años Bisiesto y no Bisiesto</h1>
        <br /> <br />
        <div>
            @using (Html.BeginForm("visualizar", "Bisiesto", FormMethod.Post))
            {
                <div>
                    @*Html.Label("Año inicial: ")*@
                    @Html.LabelFor(model => model.inicio, "Año inicial: ")
                    @Html.TextBoxFor(model => model.inicio)
                </div>

                <div>
                    @Html.LabelFor(model => model.termino, "Año inicial: ")
                    @Html.TextBoxFor(model => model.termino)
                </div>

                <label>

                    @Html.RadioButton("anio", "Bisiestos", true) <label>Años Bisiestos</label>
                </label>

                <label>

                    @Html.RadioButton("anio", "No Bisiestos", true) <label>Años No Bisiestos</label>
                </label>

                <label>

                    @Html.RadioButton("anio", "No Bisiestos", true) <label>Ambos</label>
                </label>

                <br /><br />
                <input type="submit" value="Gnenerar" />
                <br /><br />

            }
        </div>
    </div>
</body>
</html>

lab2_MVC_Laura/Views/Bisiesto/Visualizar.cshtml
@model lab2_MVC_Laura.Models.ClaseBisiesto 
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Visualizar</title>
</head>
<body>
    <div> 
        <h1>Años Bisiesto y no Bisiesto</h1>
        <br /><br/>
        @{ 
            Model.bisiesto = "";
            Model.nobisisesto = "";
            Model.resultado = "";

            for(int i= Model.inicio; i <= Model.termino;i++)
            {
                Model.Todo += i + ",";

                if(i % 400 == 0)
                {
                    Model.bisiesto = Model.bisiesto + i + "\n";
                }
                else if (i % 400 == 0 && i % 100 != 0)
                {

                }
                else
                {
                    Model.nobisisesto += i + "\n";
                }
            }

            if (Request["Anio"] == "Bisiestos"){ Model.resultado = Model.bisiesto; }

            if (Request["Anio"] == "No Bisiestos"){ Model.resultado = Model.nobisisesto; }

            if (Request["Anio"] == "Ambos"){ Model.resultado = Model.Todo; }

        }

        <h2><strong>@Request["Anio"]</strong></h2>
        <div><strong>@Model.resultado</strong></div>
        <a href="javascript:history.back()"><< Retornar al Contenido</a>
    </div>
</body>
</html>

lab2_MVC_Laura/Views/Persona/Index.cshtml
@model IEnumerable<lab2_MVC_Laura.Models.ClsPersona>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <center>
            <h1>Lista de Persona</h1>
            <br /><br />
            <table border="1" bordercolor="#0000FF">
            <tr>
                <th>Apellidos</th>
                <th>Nombres</th>
                <th>Email</th>
                <th>Sexo</th>
                <th>Edad</th>
                <th>Talla</th>
            </tr>


            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.apellido)</td>
                    <td>@Html.DisplayFor(modelItem => item.nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.email)</td>
                    <td>@Html.DisplayFor(modelItem => item.sexo)</td>
                    <td>@Html.DisplayFor(modelItem => item.edad)</td>
                    <td>@Html.DisplayFor(modelItem => item.talla)</td>
                </tr>
            }
            </table>
            <br /><br />
        </center>

    </div>

</body>
</html>

lab2_MVC_Laura/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>